CREATE TABLE IF NOT EXISTS UNITS(
	ID IDENTITY NOT NULL PRIMARY KEY, 
	ICON_LINK VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	QTY INT NOT NULL,
	UNIT_TYPE VARCHAR(1) NOT NULL,
	UNIT_ID INT NOT NULL,
	STATUS VARCHAR(1) NOT NULL);
	
CREATE TABLE IF NOT EXISTS COUNTRIES(
	ID IDENTITY NOT NULL PRIMARY KEY, 
	COUNTRY_ID INT NOT NULL,
	MAP_LINK VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	STATUS VARCHAR(1) NOT NULL);

CREATE TABLE IF NOT EXISTS DEPLOYMENTS(
	ID IDENTITY NOT NULL PRIMARY KEY, 
	COUNTRY_ID INT NOT NULL,
	UNIT_ID INT NOT NULL,
	UNIT_QTY INT NOT NULL);